package com.google.sand;

import android.content.Context;
import android.content.SharedPreferences;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;

public final class Facts {
    static String facts  []= {
            " Whale milk has 30-50% fat content and often has the consistency of a toothpaste.",
            "The nail on the middle finger grows faster than the other fingernails." ,
            "Fingernails grow nearly four times faster than toenails",
            "The brain is more active at night than during the day. Scientists don't know yet why this is.",
            "The higher your IQ, the more you supposedly dream.",
            "Facial hair grows faster than any other hair on the body.",
            "The lifespan of a human hair is 3 to 7 years on average.",
            "The acid in your stomach is strong enough to dissolve zinc. It doesn't destroy the stomach because the stomach walls constantly renew themselves.",
            "Women's hearts beat faster than men's.",
            "Women blink twice as many times as men do.",
            "Women are born better smellers than men and remain better smellers over life.",
            "Men burn fat faster than women by a rate of about 50 calories a day.",
            "Men get hiccups more often than women.",
            "A man has approximately 6.8 liters of blood in the body while women have approximately 5 liters.",
            "The largest cell in the body is the female egg and the smallest is the male sperm.",
            "During your lifetime, you will produce enough saliva to fill two swimming pools.",
             "Babies are born with blue eyes more than any other color. The melanin in their eyes needs time to be fully deposited or to be darkened by ultraviolet light to reveal the baby's true eye color.",
                    "Men have erections every hour to hour and a half during sleep. This is because the combination of blood circulation and testosterone production can cause erections during sleep and are a necessary part of REM sleep.",
                    "Your nose shapes the sound of your voice.",
                    "Your tongue can get fat.",
                    "Noise causes the pupils of your eyes to dilate. Even very small noises can do this.",
                    "Everyone has a unique smell, unique fingerprint, and unique tongue print.",
                    "By age 60, most people will have lost half their taste buds.",
                    "Your eyes remain the same size after birth but your nose and ears never stop growing.",
                    "A simple, moderately severe sunburn burns the blood vessels extensively.",
                    "We are about 1cm taller in the mornings than in the evenings.",
                    "The strongest muscle in the body is the human tongue. ",
                    "The hardest bone in the human body is the jawbone.",
                    "The hands and feet contain almost half of the total bones in the human body.",
                    "About 32 million bacteria call every inch of your skin home, but they are mostly harmless and some of them are even helpful.",
                    "Humans shed and regrow outer skin every 27 days.",
                    "The first ever cell that originated on Earth was a Prokaryotic cell.",
                    "The colder the room you sleep in, the higher the chances are that you would get a nightmare.",
                    "Humans are the only species that produce emotional tears.",
                    "All babies are color blind at birth, they see only black and white.",
                    "The only part of your body that has no blood supply is the cornea in the eye. It gets its oxygen directly from air.",
                    "A normal human being can survive 20 days without eating but can survive only 2 days without drinking.",
                    "It is impossible to kill yourself by choking yourself with your hands.",
                    "Everybody has one strong eye and one weak eye.",
                    "Your skeleton keeps renewing itself every ten years, which means that every ten years you get a new skeleton.",
                    "The human feet have 500,000 sweat glands and can produce more than a pint of sweat a day.",
                    "Nerve impulses can travel as fast as 170 miles per hour.",
                    "Your brain is more active at night.",
                    "The average person loses between 60 and 100 strands of hair each day.",
                    "A human hair can support 3.5 ounces.",
                    "Three hundred million of your body's cells die every minute.",
                    "Blonde people have more hair.",
                    "300 billion new cells are created each day.",
                    "Your body contains enough iron to make a 3-inch nail.",
                    "Blood type 'O' is the most common blood type in the world.",
                    "Tears and mucus contain an enzyme called lysozyme which breaks down the cell wall of many kinds of bacteria.",
                    "On average, right-handed people live up to 9 years longer than lefties.",
                    "It is impossible to tickle yourself.",
                    "You create more earwax when you are afraid.",
                    "The body heat you produce in half an hour is enough to boil half a gallon of water.",
                    "Lips are reddish due to a large number of capillaries hidden under the skin.",
                    "Pound for pound, bone is actually stronger than steel.",
                    "You need to use 200 muscles to take a single step.",
                    "The only part of the body that can't repair itself is the tooth.",
                    "It takes 43 muscles to frown, but only 17 to smile!",
                    "Babies have 300 bones, while adults only have 206.",
                    "More than 9 out of 10 diseases are caused or aggravated by stress.",
                    "Heart attacks are 20% more likely to occur on Mondays.",
                    "By the age of 60, 40% of women and 60% of men will snore regularly.",
                    "Identical twins have the same natural smell.",
                    "A nose can remember up to 50,000 unique scents.",
                    "There are actually 14 different basic nose shapes.",
                    "Approximately a third of humanity has 20-20 vision.",
                    "Your eyes start to develop two weeks after you are conceived.",
                    "Everyone once spent around half an hour as a single cell.",
                    "One out of every 2,000 babies is born with at least one tooth.",
                    "You lose about 4kg of skin cells each year.",
                    "Your teeth begin to grow around 6 months before birth.",
                    "The average person farts around 14 times a day.",
                    "Your feet can produce over a pint of sweat each day.",
                    "Around 75% of human waste is composed of water.",
                    "A full bladder can swell to the size of a softball.",
                    "Germs from coughs travel at around 60 miles per hour.",
                    "Human hair is practically indestructible.",
                    "The small intestine is the biggest internal organ.",
                    "A sneeze is able to travel at over 100 miles per hour.",
                    "Only after you've lost more than half of your hair will people begin to notice.",
                    "Your stomach acid is powerful enough to dissolve a razor blade.",
                    "Your body has around 60,000 miles of blood vessels.",
                    "Your stomach lining renews itself every 3-4 days.",
                    "A human lung's surface area is roughly the same as that of a tennis court.",
                    "The liver has over 500 unique functions.",
                    "Your adrenal glands keep changing size throughout your life.",
                    "Your right lung is larger than your left lung.",
                    "The aorta has a diameter that's similar to that of a garden hose.",
                    "Your brain can store five times the amount of information as the Encyclopedia Britannica.",
                    "Your brain itself is unable to experience pain.",
                    "Around 10,000 human cells could fit on a pin head.",
                    "It is the waste products of sweat, and not sweat itself, that smell bad.",
                    "A passionate kiss causes the same chemical reactions to take place that firing a gun and bungee jumping do.",
                    "A drop of blood contains around 250,000 platelets.",
                    "You have taste buds other places besides your tongue.",
                    "You have approximately 2,000 different taste buds.",
                    "Children grow faster in the spring.",
                    "Your eyes can distinguish around 10 million different hues.",
                    "Ingrown toenails are hereditary.",
                    "Your memory is affected by your body position, meaning that you remember things differently when you're standing to when you're sitting.",
                    "Your brain can make your think you are hearing loud noises in a condition known as 'exploding head syndrome'.",
                    "You use around 200 different muscles in order to take a single step forward.",
                    "Men also have a uterus, which lies dormant on one side of the male prostate gland.",
                    "Similarly, women's bodies also contain an undeveloped vas deferens.",
                    "The pinkie toe is largely unnecessary in today's world, and some evolutionary scientists think that it will eventually be lost to evolution.",
                    "The brain physically changes shape during puberty.",
                    "A quarter of the bones in your body are found in your feet." ,
                    "Pound for pound, babies are stronger than oxen!" ,
                    "Adrenaline can give you a temporary strength boost.",
                    "A bite from a human being will almost always become infected if left untreated.",
                    "A human fetus is able to heal its mother's wounds.",
                    "Your fingers don't contain a single muscle.",
                    "Your body contains around 2kg of bacteria.",
                    "Your body contains enough blood to satisfy the appetites of 1,200,000 mosquitoes.",
                    "When you blush, your stomach lining blushes with you.",
                    "Fingertips are actually capable of regrowing.",
                    "Your eyes see the world upside down, but the brain automatically corrects it for you.",
                    "Your sense of smell is the last sense to activate each morning.",
                    "Your body contains ten times more bacteria cells than human cells.",
                    "Every year about 98% of atoms in your body are replaced.",
                            "At a glance, the Celsius scale makes more sense than the Fahrenheit scale for temperature measuring. But its creator, Anders Celsius, was an oddball scientist. When he first developed his scale, he made freezing 100 degrees and boiling 0 degrees, or upside down. No one dared point this out to him, so fellow scientists waited until Celsius died to change the scale.",
                            "In Gulliver's Travels Jonathan Swift described the two moons of Mars, Phobos and Deimos, giving their exact size and speeds of rotation. He did this more than 100 years before either moon was discovered.",
                            "At a jet plane's speed of 1,000 km (620mi) per hour, the length of the plane becomes one atom shorter than its original length.",
                            "In the Durango desert, in Mexico, there's a creepy spot called the \"Zone of Silence.\" You can't pick up clear TV or radio signals. And locals say fireballs sometimes appear in the sky.",
                            "Ethernet is a registered trademark of Xerox, Unix is a registered trademark of AT&T.",
                            "Bill Gates' first business was Traff-O-Data, a company that created machines which recorded the number of cars passing a given point on a road.",
                            "Uranus' orbital axis is tilted at 90 degrees.",
                            "The final resting-place for Dr. Eugene Shoemaker - the Moon. The famed U.S. Geological Survey astronomer, trained the Apollo astronauts about craters, but never made it into space. Mr. Shoemaker had wanted to be an astronaut but was rejected because of a medical problem. His ashes were placed on board the Lunar Prospector spacecraft before it was launched on January 6, 1998. NASA crashed the probe into a crater on the moon in an attempt to learn if there is water on the moon.",             "Outside the USA, Ireland is the largest software producing country in the world.",
                            "The first fossilized specimen of Australopithecus afarenisis was named Lucy after the paleontologists' favorite song \"Lucy in the Sky with Diamonds,\" by the Beatles.",
                            "Figlet, an ASCII font converter program, stands for Frank, Ian and Glenn's LETters.",
                            "Every human spent about half an hour as a single cell.",
                            "Plutonium - first weighed on August 20th, 1942, by Univ0ersity of Chicago scientists Glenn Seaborg and his colleagues - was the first man-made element.",
                            "The radioactive substance, Americanium - 241 is used in many smoke detectors.",
                            "The original IBM-PCs, that had hard drives, referred to the hard drives as Winchester drives. This is due to the fact that the original Winchester drive had a model number of 3030. This is, of course, a Winchester firearm.",
                            "Sound travels 15 times faster through steel than through the air.",
                            "On average, half of all false teeth have some form of radioactivity.",
                            "Only one satellite has been ever been destroyed by a meteor: the European Space Agency's Olympus in 1993.",
                            "Starch is used as a binder in the production of paper. It is the use of a starch coating that controls ink penetration when printing. Cheaper papers do not use as much starch, and this is why your elbows get black when you are leaning over your morning paper.",
                            "Sterling silver is not pure silver. Because pure silver is too soft to be used in most tableware it is mixed with copper in the proportion of 92.5 percent silver to 7.5 percent copper.",
                            "A ball of glass will bounce higher than a ball of rubber. A ball of solid steel will bounce higher than one made entirely of glass.",
                            "A chip of silicon a quarter-inch square has the capacity of the original 1949 ENIAC computer, which occupied a city block.",
                            "An ordinary TNT bomb involves atomic reaction, and could be called an atomic bomb. What we call an A-bomb involves nuclear reactions and should be called a nuclear bomb.",
                            "The first full moon to occur on the winter solstice, Dec. 22, commonly called the first day of winter, happened in 1999. Since a full moon on the winter solstice occurred in conjunction with a lunar perigee (point in the moon's orbit that is closest to Earth), the moon appeared about 14% larger than it does at apogee (the point in it's elliptical orbit that is farthest from the Earth). Since the Earth is also several million miles closer to the sun at that time of the year than in the summer, sunlight striking the moon was about 7% stronger making it brighter. Also, this was the closest perigee of the Moon of the year since the moon's orbit is constantly deforming. In places where the weather was clear and there was a snow cover, even car headlights were superfluous.",
                            "According to security equipment spe******ts, security systems that utilize motion detectors won't function properly if walls and floors are too hot. When an infrared beam is used in a motion detector, it will pick up a person's body temperature of 98.6 degrees compared to the cooler walls and floor. If the room is too hot, the motion detector won't register a change in the radiated heat of that person's body when it enters the room and breaks the infrared beam. Your home's safety might be compromised if you turn your air conditioning off or set the thermostat too high while on summer vacation.",
                            "Western Electric successfully brought sound to motion pictures and introduced systems of mobile communications which culminated in the cellular telephone.",
                            "On December 23, 1947, Bell Telephone Laboratories in Murray Hill, N.J., held a secret demonstration of the transistor which marked the foundation of modern electronics.",
                            "The wick of a trick candle has small amounts of magnesium in them. When you light the candle, you are also lighting the magnesium. When someone tries to blow out the flame, the magnesium inside the wick continues to burn and, in just a split second (or two or three), relights the wick.",
                            "Time slows down near a black hole; inside it stops completely",
                            "Tiny dust particles surround a comet. They are swept into a long tail by the solar wind, which consists of subatomic particles speeding from the sum at speed of hundred of miles per second.",
                            "To an observer standing on Pluto, the sun would appear no brighter than Venus appears in our evening sky.",
                            "Traveling at the speed of 186,000 miles per second, light take 6 hours to travel from Pluto to the earth.",
                            "A brown dwarf is a very small, dark object, with a mass less than 1/10 that of the Sun. They are 'failed stars', globules of gas that have shrunk under gravity, but failed to ignite and shine as stars.",
                            "If you have 3 quarters, 4 dimes, and 4 pennies, you have $1.19. You also have the largest amount of money in coins without being able to make change for a dollar. ",
                            "The numbers '172' can be found on the back of the U.S. $5 dollar bill in the bushes at the base of the Lincoln Memorial. ",
                            "President Kennedy was the fastest random speaker in the world with upwards of 350 words per minute. ",
                            "In the average lifetime, a person will walk the equivalent of 5 times around the equator. ",
                            "Odontophobia is the fear of teeth.",
                            "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.",
                            "In the early days of the telephone, operators would pick up a call and use the phrase, \"Well, are you there?\". It wasn't until 1895 that someone suggested answering the phone with the phrase \"number please?\" ",
                            "The surface area of an average-sized brick is 79 cm squared. ",
                            "According to suicide statistics, Monday is the favored day for self-destruction.",
                            "Cats sleep 16 to 18 hours per day. ",
                            "The most common name in the world is Mohammed.",
                            "It is believed that Shakespeare was 46 around the time that the King James Version of the Bible was written. In Psalms 46, the 46th word from the first word is shake and the 46th word from the last word is spear. ",
                            "Karoke means \"empty orchestra\" in Japanese. ",
                            "The Eisenhower interstate system requires that one mile in every five must be straight. These straight sections are usable as airstrips in times of war or other emergencies. ",
                             "The first known contraceptive was crocodile dung, used by Egyptians in 2000 B.C. ",
                            "Rhode Island is the smallest state with the longest name. The official name, used on all state documents, is \"Rhode Island and Providence Plantations.\" ",
                            "When you die your hair still grows for a couple of months. ",
                            "There are two credit cards for every person in the United States.",
                            "Isaac Asimov is the only author to have a book in every Dewey-decimal category. ",
                            "The newspaper serving Frostbite Falls, Minnesota, the home of Rocky and Bullwinkle, is the Picayune Intellegence.",
                            "It would take 11 Empire State Buildings, stacked one on top of the other, to measure the Gulf of Mexico at its deepest point.",
                            "The first person selected as the Time Magazine Man of the Year - Charles Lindbergh in 1927.",
                            "The most money ever paid for a cow in an auction was $1.3 million.",
                            "It took Leo Tolstoy six years to write \"War & Peace\".",
                            "The Neanderthal's brain was bigger than yours is.",
                            "On the new hundred dollar bill the time on the clock tower of Independence Hall is 4:10.",
                            "Each of the suits on a deck of cards represents the four major pillars of the economy in the middle ages: heart represented the Church, spades represented the military, clubs represented agriculture, and diamonds represented the merchant class. ",
                             "The names of the two stone lions in front of the New York Public Library are Patience and Fortitude. They were named by then-mayor Fiorello LaGuardia.",
                            "The Main Library at Indiana University sinks over an inch every year because when it was built, engineers failed to take into account the weight of all the books that would occupy the building.",
                            "The sound of E.T. walking was made by someone squishing her hands in jelly.",
                            "Lucy and Linus (who where brother and sister) had another little brother named Rerun. (He sometimes played left-field on Charlie Brown's baseball team, [when he could find it!]). ",
                            "The pancreas produces Insulin.",
                            "1 in 5,000 north Atlantic lobsters are born bright blue.",
                            "There are 10 human body parts that are only 3 letters long (eye hip arm leg ear toe jaw rib lip gum).",
                            "A skunk's smell can be detected by a human a mile away.",
                            "The word \"lethologica\" describes the state of not being able to remember the word you want. ",
                            "The king of hearts is the only king without a moustache. ",
                            "Henry Ford produced the model T only in black because the black paint available at the time was the fastest to dry. ",
                            "Mario, of Super Mario Bros. fame, appeared in the 1981 arcade game, Donkey Kong. His original name was Jumpman, but was changed to Mario to honor the Nintendo of America's landlord, Mario Segali.",
                            "The three best-known western names in China: Jesus Christ, Richard Nixon, and Elvis Presley.",
                            "Every year about 98% of the atoms in your body are replaced.",
                            "Elephants are the only mammals that can't jump.",
                            "The international telephone dialing code for Antarctica is 672.",
                            "World Tourist day is observed on September 27.",
                            "Women are 37% more likely to go to a psychiatrist than men are.",
                            "The human heart creates enough pressure to squirt blood 30 feet (9 m).",
                            "Diet Coke was only invented in 1982.",
                            "There are more than 1,700 references to gems and precious stones in the King James translation of the Bible. ",
                            "When snakes are born with two heads, they f0ight each other for food.",
                            "American car horns beep in the tone of F.",
                            "Turning a clock's hands counterclockwise while setting it is not necessarily harmful. It is only damaging when the timepiece contains a chiming mechanism.",
                            "There are twice as many kangaroos in Australia as there are people. The kangaroo population is estimated at about 40 million.",
                            "Police dogs are trained to react to commands in a foreign language; commonly German but more recently Hungarian.",
                            "The Australian $5 to $100 notes are made of plastic.",
                            "St. Stephen is the patron saint of bricklayers.",
                            "The average person makes about 1,140 telephone calls each year.",
                            "Stressed is Desserts spelled backwards.",
                            "If you had enough water to fill one million goldfish bowls, you could fill an entire stadium.",
                            "Flying from London to New York by Concord, due to the time zones crossed, you can arrive 2 hours before you leave.",
                            "Dentists have recommended that a toothbrush be kept at least 6 feet (2 m) away from a toilet to avoid airborne particles resulting from the flush.",
                            "You burn more calories sleeping than you do watching TV.",
                            "A lion's roar can be heard from five miles away.",
                            "The citrus soda 7-UP was created in 1929; \"7\" was selected because the original containers were 7 ounces. \"UP\" indicated the direction of the bubbles.",
                            "Canadian researchers have found that Einstein's brain was 15% wider than normal.",
                            "The average person spends about 2 years on the phone in a lifetime.",
                            "The fist product to have a bar code was Wrigleys gum. ",
                            "The largest number of children born to one woman is recorded at 69. From 1725-1765, a Russian peasant woman gave birth to 16 sets of twins, 7 sets of triplets, and 4 sets of quadruplets.",
                            "Beatrix Potter created the first of her legendary \"Peter Rabbit\" children's stories in 1902. " ,
                            "In ancient Rome, it was considered a sign of leadership to be born with a crooked nose. ",
                            "The word \"nerd\" was first coined by Dr. Seuss in \"If I Ran the Zoo.\" ",
                            "A 41-gun salute is the traditional salute to a royal birth in Great Britain.",
                            "The bagpipe was originally made from the whole skin of a dead sheep.",
                            "The roar that we hear when we place a seashell next to our ear is not the ocean, but rather the sound of blood surging through the veins in the ear. Any cup-shaped object placed over the ear produces the same effect.",
                            "Revolvers cannot be silenced because of all the noisy gasses which escape the cylinder gap at the rear of the barrel",
                            "Liberace Museum has a mirror-plated Rolls Royce; jewel-encrusted capes, and the largest rhinestone in the world, weighing 59 pounds and almost a foot in diameter.",
                            "A car that shifts manually gets 2 miles more per gallon of gas than a car with automatic shift.",
                            "Cats can hear ultrasound. ",
                            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
                            "The highest point in Pennsylvania is lower than the lowest point in Colorado.",
                            "The United States has never lost a war in which mules were used.",
                            "On average, there are 178 sesame seeds on each McDonalds BigMac bun.",
                            "Paul Revere rode on a horse that belonged to Deacon Larkin.",
                            "The Baby Ruth candy bar was actually named after Grover Cleveland's baby daughter, Ruth.",
                            "Minus 40 degrees Celsius is exactly the same as minus 40 degrees Fahrenheit.",
                            "Clans of long ago that wanted to get rid of unwanted people without killing them used to burn their houses down -- hence the expression \"to get fired\" ",
                            "Nobody knows who built the Taj Mahal. The names of the architects, masons, and designers that have come down to us have all proved to be latter-day inventions, and there is no evidence to indicate who the real creators were.",
                            "Every human spent about half an hour as a single cell.",
                            "7.5 million toothpicks can be created from a cord of wood.",
                            "The plastic things on the end of shoelaces are called aglets." ,
                            "A 41-gun salute is the traditional salute to a royal birth in Great Britain. \n" +
                            "The earliest recorded case of a man giving up smoking was on April 5, 1679, when Johan Katsu, Sheriff of Turku, Finland, wrote in his diary \"I quit smoking tobacco.\" He died one month later.",
                            "\"Goodbye\" came from \"God bye\" which came from \"God be with you.\" ",
                            "February is Black History Month.",
                            "Jane Barbie was the woman who did the voice recordings for the Bell System.",
                            "The first drive-in service station in the United States was opened by Gulf Oil Company - on December 1, 1913, in Pittsburgh, Pennsylvania.",
                            "The elephant is the only animal with 4 knees. Kansas state law requires pedestrians crossing the highways at night to wear tail lights.",
                            "No piece of normal-size paper can be folded in half more than 7 times.",
                            "80% of all pictures on the internet are of naked women",
                            "250 to 300 million cell phones are being used in the U.S.",
                            "During good sex, endorphines are released, which are powerful painkillers. So headaches are in fact a bad excuse not to have sex",
                            "The shrimp's heart is in its head",
                            "It is impossible to sneeze with your eyes open",
                            "The skin of the average woman weighs 3 kilograms, while that of the average man weighs 5 kilograms",
                            "Dutch, on average are the tallest people",
                            "Kissing is healthier than shaking hands ",
                            "There are no cemeteries in San Francisco, CA",
                            "India never invaded any country in her history",
                            "Natural pearls melt in vinegar",
                            "An olive tree can live up to 1500 years",
                            "Cleopatra married two of her brothers ",
                            "Buttermilk does not contain any butter",
                            "Before toilet paper was invented, French royalty wiped their bottoms with fine linen ",
                            "The earth is about 6,588,000,000,000,000,000 tons in weight",
                            "A goldfish has a memory span of about 3 seconds",
                            "There are 86,400 seconds in day",
                            "The parachute was invented by DiVinci in 1515",
                            "Ants never sleep",
                            "The human brain is 80% water",
                            "On a Canadian two dollar bill, the flag flying over the Parliament Building is an American flag ",
                            "No word in the English language rhymes with month, orange, silver or purple ",
                            "Marilyn Monroe had six toes on one foot",
                            "If you keep a Goldfish in the dark room, it will eventually turn white",
                            "The phrase \"rule of thumb\" is derived from an old English law that stated you couldn't beat your wife with anything wider than your thumb",
                            "'Jedi' is an official religion in Australia with over 70,000 followers",
                            "Church of England has apologized to Charles Darwin 200 years after his birth",
                            "Chewing gum while peeling onions will reduce your tears",
                            "Dalmatians are born without spots",
                            "Men’s shirts have the buttons on the right while women’s shirts have the buttons on the left",
                            "Roosters have to extend their necks in order to crow",
                            "Winston Churchill was born in a ladies' room ",
                            "Armadillos have four babies at a time and they are always all the same sex",
                            "In 2009 one of eight newly married couples in the US met online",
                            "There are about 540,000 words in the English language and growing ",
                            "Gamblers mostly don't see any clocks in Las Vegas gambling casinos ",
                            "If you are right handed, you will tend to chew food on your right side. If you are left handed, you likely to chew food on your left side",
                            "The bedroom is the most common place for sex and the car is second ",
                            "Humans and bonobo monkeys (pygmy chimpanzee) are the only species who have face-to-face sex",
                            "Everyday, 15 billion cigarettes are smoked worldwide",
                            "Hugo Boss designed some of the Nazi SS uniforms ",
                            "Any free moving liquid in outer space will form itself into a sphere, because of its surface tension",
                            "A snail can slide over a razor blade without being hurt by producing slime that helps it slide harmlessly ",
                            "Worldwide, there are approximately 100 million acts of sexual intercourse each day",
                            "Women blink nearly twice as much as men",
                            "The human heart beats over 100,000 times a day ",
                            "Human fingernails grow nearly 4 times faster than toenails",
                            "The French tickler was invented by a Tibetan monk ",
                            "Studies have proven that it is harder to tell a convincing lie to someone you find sexually attractive ",
                            "Onions have no flavor, only a smell",
                            "Red wine will spoil if exposed to light; hence tinted bottles",
                            "One quarter of the bones in the human body is in the feet",
                            "Dogs and cats, like humans, are either right or left handed (paw).",
                            "Polar bears with white, fluffy fur actually have black skin",
                            "Sharks lay the biggest eggs in the world",
                            "The blue whale can produce the loudest sound of any animal. At 188 decibels, the noise can be detected over 800 kilometres away",
                            "The day after Thanksgiving is the busiest day for plumbers in the US",
                            "The eyes of the chameleon can move independently. It can see in two different directions at the same time",
                            "The total weight of skin for an average adult human is 6 pounds. ",
                            "The world record for time without sleep is 264 hours ( ~11 days) by Randy Gardner in 1965 ",
                            "Cold showers stimulate your sex drive",
                            "Coffee beans aren't beans; they are fruit pits ",
                            "Among older men, vanilla is the most erotic smell ",
                            "A pound of potato chips costs 200 times more than a pound of raw potatoes ",
                            "Lima beans contain cyanide ",
                            "Fortune cookies were actually invented in America (not China), in 1918, by Charles Jung ",
                            "If you put a raisin in a fresh glass of champagne, it will rise and fall continuously",
                            "Caffeine is on the International Olympic Committee list of prohibited substances ",
                            "Some in Japan bath in coffee grounds that were fermented with pineapple pulp to improve their skin and reduce wrinkles ",
                            "Some kinds of frogs can be frozen solid then thawed, and continue living ",
                            "A snail can sleep for three years " ,
                            "February 1865 is the only month in recorded history not to have a full moon ",
                            "In Korea and other East Asian countries, the age of the person is counted from conception and not physical birth ",
                            "Dogs have about 10 vocal sounds; cats have over 100 ",
                            "The people in Bali only have one of four names: Wayan, Made, Nyoman, and Ketut ",
                            "There are more pyramids in Peru than in Egypt ",
                            "The Great Pyramid at Giza in Egypt holds a constant temperature of 68 degrees Fahrenheit ",
                            "The state official motto of Alaska is \" North to the Future\" ",
                            "People who chase after rare birds are called twitchers",
                            "In ancient Egypt, priests plucked every hair from their bodies",
                            "Orgies were originally religious events. They were originally offerings to the gods",
                            "2,520 can be divided by 1, 2, 3, 4, 5, 6, 7, 8, 9, and 10 without having a fractional leftover",
                            "It is unknown if odd perfect numbers exist",
                            "A perfect number is a number whose divisors add up to itself such as 28: 1+2+4+7+14=28 ",
                            "Human eye detects 10 million colors",
                            "The word \"Checkmate\" in chess comes from the Persian phrase \"Shah Mat,\" which means \"the king (shah) is dead (mat).\" ",
                            "Kissing helps prevent tooth decay",
                            "One California law states that sunshine is guaranteed to all people ",
                            "Moderate dancing burns 250 to 300 calories an hour ",
                            "Your thumb is the same length as your nose ",
                            "Butterflies smell with their feet ",
                            "Canada is an Indian word meaning \"Big Village\" ",
                            "A pregnant goldfish is called a twit",
                            "In Hong Kong, a betrayed wife is legally allowed to kill her cheating adulterous husband but she may only do so with her bare hands",
                            "In Germany, an official approval is needed before a new born is named.",
                            "Infants spend more time dreaming than adults do ",
                            "Impotence is grounds for divorce in 26 U.S. states ",
                            "Horses can't vomit and pigs can't look up in the sky ",
                            "In1770, a bill proposing that women using makeup should be punished for witchcraft was put forward to the British Parliament ",
                            "The oldest dog died at the age of 29 ",
                            "Cats are the most popular pets in the United States ",
                            "Black olives contain on average 10 to 30% more oil than green olives",
                            "In Arizona it is illegal to have more than two dildos in one house",
                            "San Jose was the original capital of California",
                            "Carl Sagan was a pot smoker",
                            "5% of the world population lives in the US but 22% of the world's prisons population are held in the US.",
                            "All swans in England are the property of the queen or king",
                            "The first product to have a bar code scanned was Wrigley's gum.",
                            "Earth is the only planet not named after a pagan God. ",
                            "A Boeing 747s wingspan is longer than the Wright brother's first flight.",
                            "In Hong Kong, a betrayed wife is legally allowed to kill her cheating adulterous husband but she may only do so with her bare hands.",
                            "The new 787 Boeing was revealed on 7/8/07 or July 8th, 07. ",
                            "Adding a drop of olive oil and lemon juice to an ice cube then running it over your face gives you better results than some expensive skin care products.",
                            "250 to 300 million cell phones are being used in the U.S",
                            "You will weigh less if you weigh yourself when the moon is full",
                            "Honeybees never sleep ",
                            "Carl Sagan was a pot smoker",
                            "Benjamin Franklin was offended about putting a bald eagle as the national bird because he thought that other people were trying to make fun of him, since he was bald ",
                             "5% of the world population lives in the US but 22% of the world's prisons population are held in the US ",
                            "80% of all pictures on the internet are of naked women ",
                            "Horses can't vomit and pigs can't look up in the sky ",
                            "San Jose was the original capital of California ",
                            "Most lipstick have fish scales ",
                            "In Arizona it is illegal to have more than two dildos in one house ",
                            "Black olives contain on average 10 to 30% more oil than green olives ",
                            "Cats are the most popular pets in the United States ",
                            "The oldest dog died at the age of 29",
                            "Tamiflu's main natural ingredient is Chinese star anise",
                            "Not only the fur of the tiger is striped but also its skin ",
                            "The Germans tried to copy Coca-Cola and came up with the drink Fanta. ",
                            "Every day is about 55 billionths of a second longer than the day before it",
                            "Venus is the only planet that rotates clockwise.",
                            "The largest potato was grown in Lebanon by Khalil Semhat near Tyre. The spud was 11.3 kilos (24.9 pounds)",
                            "Footprints of astronauts who landed on the moon should last at least 10 million years since the moon has no atmosphere. ",
                            "The national orchestra of Monaco (a nation in Europe) has more individuals than its army. ",
                            "Earthworms have five hearts " ,
                            "The Himalayan gogi berry contains, weight for weight, more iron than steak, more beta carotene than carrots, more vitamin C than oranges. ",
                            "Paraguay and Moldova are the only countries with national flags with different emblems on the obverse and reverse sides. ",
                            "Fingerprints of koalas are similar (in pattern, shape and size) to the fingerprints of humans ",
                            "Genetically-engineered babies were born first in 2001. ",
                            "If an Amish man has a beard, he is married. ",
                            "If a native Hawaiian woman places the flower on her right ear, she is available. (The bigger the flower, the more desperate) ",
                            "Apples, not caffeine, are more efficient at waking you up in the morning. ",
                            "Pope Pius II wrote an erotic book \"Historia de duobos amantibus\" in 1444. ",
                            "SCUBA divers cannot pass gas at depths of 33 feet or below ",
                            "Pele has always hated his nickname, which he says sounds like \"baby-talk in Portuguese\". ",
                            "As of 2006, 200 million blogs were left without updates ",
                            "Two phone books with their pages interlaced require more than 8000 pounds of pressure to separte. ",
                            "Urban birds have developed a short, fast \"rap style\" of singing, different from their rural counterparts. ",
                            "The lion costume in the film Wizard of Oz was made from real lions. ",
                            "Fathers tend to determine the height of their child, mothers their weight.",
                            "The Pope's been known to wear red Prada shoes. ",
                            "Donald Rumsfeld was both the youngest and the oldest defense secretary in US history. ",
                            "Coco Chanel started the trend for sun tans in 1923 when she got accidentally burnt on a cruise. ",
                            "Up to 25% of hospital keyboards carry the MRSA infection.",
                            "In ancient Greece, children of wealthy families were dipped in olive oil at birth to keep them hairless throughout their lives.",
                            "Ghandi didn't allow his wife to take penicillin to save her life from pneumonia but took quinine to save himself from malaria. ",
                            "Sex workers (Prostitutes) in Roman times charged the equivalent price of eight glasses of red wine.",
                            "As of 2006, more than one in eight people in the United States show signs of addiction to the internet.",
                            "More than 90% of plane crashes have survivors. ",
                            "The Mona Lisa used to hang on the wall of Napoleon’s bedroom." ,
                            "Barbie's full name is Barbie Millicent Roberts." ,
                            "Eating a packet of crisps a day is equivalent to drinking five liters of cooking oil a year.",
                            "Plant seeds that have been stored for more than 200 years can be coaxed into new life.",
                            "For every 10 successful attempts to climb Mount Everest there is one fatality. (As of 2006) ",
                            "Watching television can act as a natural painkiller for children ",
                            "Forty-one percent of English women have punched or kicked their partners, according to a study. " ,
                            "The more panels a football has - and therefore the more seams - the easier it is to control in the air." ,
                            "Music can help reduce chronic pain by more than 20% and can alleviate depression by up to 25%. ",
                            "Modern teenagers are better behaved than their counterparts of 20 years ago, showing \"less problematic behavior\" involving sex, drugs and drink.",
                            "Britain is still paying off debts that predate the Napoleonic wars because it's cheaper to do so than buy back the bonds on which they are based.",
                            "In Bhutan government policy is based on Gross National Happiness; thus most street advertising is banned, as are tobacco and plastic bags.",
                            "The best-value consumer purchase in terms of the price and usage is an electric kettle. ",
                            "Camel's milk, which is widely drunk in Arab countries, has 10 times more iron than cow's milk. ",
                            "Iceland has the highest concentration of broadband users in the world.",
                            "Native Hawaiian women were not allowed to cook. ",
                            "The age limit for marriage in France was, until recently, 15 for girls, but 18 for boys. The age for girls was raised to 18 in 2006.",
                            "The brain is soft and gelatinous - its consistency is something between jelly and cooked pasta.",
                            "The Himalayas cover one-tenth of the Earth's surface."
    };

    static int i = 0;
    static String prefName = "facts";
    static SimpleDateFormat ft = new SimpleDateFormat("yyyy-MM-dd");

    public static String nextFact(){
        i++;

        if(i >= facts.length){
            i = 0;
        }
        return facts[i];
    }

    public static String prevFact(){
        i--;
        if(i < 0){
            i = facts.length;
        }
        return facts[i];
    }


    public static String randFact() {
        return facts[(new Random()).nextInt(facts.length) + 1];
    }

    public static String dailyFact(Context con) {
        return prevDaily(con, 0);
    }

    public static String prevDaily(Context con, int day) {
        SharedPreferences dailies = con.getSharedPreferences(prefName, 0);

        String dateString = ft.format(new Date((new Date()).getTime() - day * 24 * 60 * 60 * 1000L));
        if (dailies.contains(dateString)) {
            return facts[dailies.getInt(dateString, 0)];
        } else {
            SharedPreferences.Editor edit = dailies.edit();
            int v = (new Random()).nextInt(facts.length) + 1;
            edit.putInt(dateString, v);
            edit.apply();
            return facts[v];
        }

    }
}
